live_config_reload = true
working_directory = "None"
import = [ "~/.config/alacritty/themes/doom_one.toml" ]

[window]
title = "Alacritty"
decorations = "none"
blur = true
opacity = 0.95

[window.padding]
x = 10
y = 10

[window.dimensions]
columns = 160
lines = 80

[cursor.style]
shape = "Beam"
blinking = "Never"

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"
