#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================


# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "one"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    automatic_update = true
    enable_vimfiler_gitstatus = true 
    filetree_direction = "left"

[[layers]]
  name = "colorscheme"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = "format"

[[layers]]
name = "fzf"

[[layers]]
  name = "git"

[[layers]]
name="VersionControl"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#python"
enable_typeinfo = true

[[layers]]
name = "lang#php"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#javascript"

[[layers]]
  name = "lang#assembly"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#sql"

[[layers]]
  name = "lang#toml"
[[layers]]
  name = "ui"

[[layers]]
  name = "tools"

[[layers]]
  name = "debug"

[[layers]]
  name = "denite"

[[custom_plugins]]
repo = "rakr/vim-one"
repo = "ghifarit53/tokyonight-vim"
repo = "vim-scripts/dbext.vim"
repo = "frazrepo/vim-rainbow"
repo = "preservim/nerdcommenter"
repo = "jiangmiao/auto-pairs"
repo = "tpope/vim-surround"
repo = "mattn/emmet-vim"
repo = "tomtom/tcomment_vim"
repo = "wellle/visual-split.vim"
repo = "scrooloose/nerdtree"
repo = "turbio/bracey.vim"
repo = "sbdchd/neoformat"
repo = "dense-analysis/ale"
repo = "neoclide/coc.nvim"
repo = "Shougo/neosnippet.vim"
repo = "alvan/vim-closetag"
repo = "maxmellon/vim-jsx-pretty"
repo = "majutsushi/tagbar"
repo = "ryanoasis/vim-devicons"
repo = "dart-lang/dart-vim-plugin"
repo = "tpope/vim-fugitive"
repo = "terryma/vim-multiple-cursors"
repo = "airblade/vim-gitgutter"
repo = "wakatime/vim-wakatime"

